### ISSUE TITLE
MeetingGrid: subqueries should use LIMIT 1

### ISSUE THREAD

**Issue by vizziv** [urweb/upo#13]
I recently fixed a bug in my own fork of MeetingGrid that required adding `LIMIT 1` to the subqueries for `slot` in `scheduleSome`. Without these, scheduleSome causes a very long error message in some cases, probably to do with someone having multiple meetings in a time slot.

(I saw the buffer size increase commit for Ur/Web, which was a change I made locally as part of debugging this, so I figured I'd mention this in case it's the reason.)

**Comment by achlipala** [comment]
Well, that's an interesting case of parallel evolution.  I actually had already fixed this issue in a different way, a few hours before this issue was opened, and now I've pushed my (logically equivalent) change.
