### ISSUE TITLE
examples/onlineconf.ur hard codes adam.chlipala@gmail.com

### ISSUE THREAD

**Issue by mdempsky** [urweb/upo#17]
After following the README, I was stuck wondering why the "Log in with Google" button for onlineconf wasn't working. It looks like examples/onlineconf.ur hard codes adam.chlipala@gmail.com as the only user, and then doesn't give an error message about not being authorized?

Perhaps the admin username/email should be configurable via exampleconfSecret.ur too?

**Comment by achlipala** [comment]
Agreed!  Want to take a shot at a PR for it?
