### ISSUE TITLE
Documentation: indicate dependencies

### ISSUE THREAD

**Issue by bmsherman** [urweb/upo#4]
It would be helpful for newcomers to UPO if it were mentioned in the README or other documentation that the Ur/Web [Bootstrap library](http://hg.impredicative.com/bootstrap) and [ajaxUpload library](http://hg.impredicative.com/ajaxUpload) must be installed in order for UPO to work, and providing the relevant links to those repositories.

**Comment by achlipala** [comment]
Added.  Thanks for catching that.
