### ISSUE TITLE
bootstrap3 'carousel' with upo

### ISSUE THREAD

**Issue by bfilin** [urweb/upo#5]
Is there a recommended way that 'carousel' can be implemented with urweb's bootstrap library?

While testing carousel with upo I ended up updating bootstrap3.ur library file, adding the following:
style center_block
style item
style left
style right
style slide

I'm not sure if this is a correct thing to do.
Here is the example that seems to work: https://github.com/bfilin/upo_carousel/blob/master/cartest.ur

Thank you.

**Comment by achlipala** [comment]
Thanks for the pointers to new styles to add.  They're in the official Mercurial repo for Ur/Web Bootstrap now.

Your approach to integrating a carousel with UPO looks fine.  You could also use the `<active>` tag to combine the ID generation with the HTML generation in the same function.
