### ISSUE TITLE
meta tag with viewport 

### ISSUE THREAD

**Issue by bfilin** [urweb/upo#8]
What would be the correct and secure way to setup meta tag with 'viewport'?

I'm testing UPO with mobile devices and need support for:
`<meta` name="viewport" content="width=device-width, `initial-scale=1">`

Adding the following function to upo/navbar.js seems to resize screen as needed on mobile devices:
$(document).ready(function () {
   `$('head').append('<meta` name="viewport" content="width=device-width, `initial-scale=1"/>');`
});

I saw a post/discussion on Ur/Web mailing-list archive that mentioned security implications of meta tag, but as far as I understood it (perhaps wrongly) JavaScript on client side should be okay. I would like to avoid shoot myself in the foot with this and keep things secure. 

Thank you.

**Comment by bfilin** [comment]
Closing, I see how it is done with https://github.com/extensibl/website/blob/master/tagffi.urs
That works. Will see how to restrict this further to only allow 'viewport'.

**Comment by achlipala** [comment]
The solution you found with the FFI certainly gets the job done, but I think it's inelegant and risky.

What do you think of this proposal: extend Ur/Web with a compile-time policy on which `<meta>` names are allowed, just as HTTP headers are currently whitelisted?

The issue that motivates being so careful: I do, in fact, consider it a serious security violation to provide any built-in way of executing any string as a program in a Turing-complete language like JavaScript.  Precisely that scary situation could easily arise, if exposing `<meta>` via the "most natural" type, with strings for its attributes.  An application might unwittingly insert unsanitized user input into a `<meta>` tag, which might interpret that user input as a program in some language, breaking all sorts of abstractions that are apparent at the source level in Ur/Web.

**Comment by bfilin** [comment]
Having additional control over `<meta>` attributes via compile policy sounds good. 
Would that allow for a simple 'allow' setting in .urp file?

**Comment by achlipala** [comment]
Yes, that's the idea.

**Comment by bfilin** [comment]
'allow meta viewport' works fine with upo and the urweb-20160515 release. 
Thank you!
