### ISSUE TITLE
options for data plots/graphs

### ISSUE THREAD

**Issue by bfilin** [urweb/upo#9]
Are there any plans to add support for svg tags (or html5 canvas) to Ur/Web?

Trying to achieve the following: securely display graph/plot of data from sql table in upo.

Exploring the following options:
1) create Ur/Web functions that use div tags and css to make super-simple bar chart
   Pro: no javascript, safe/secure, easy
   Con: limited chart support: bar chart type

2) ffi to a javascript charting library. 
   Pro: many more chart types and options are supported, charts can be dynamic
   Con: javascript security issues, need to create a lot of ffi bindings
        may need canvas or svg tag (depending on library)

   e.g. toy test of plotly.js[https://plot.ly/javascript/] 
   seems to work with a div tag, but plotly's javascript appends 
   its own svg tag. 

3) create/port drawing library (most likely need svg support or html5 canvas tag).

Thank you.

**Comment by achlipala** [comment]
I think option 2 should be the most pragmatic, and I would recommend creating a separate library/repo for an FFI wrapper of a suitable JavaScript library.

Which security issues do you have in mind?

**Comment by bfilin** [comment]
I see this idea being used, for example,  with Purescript [https://github.com/slamdata/purescript-echarts]. So the goal would be to FFI wrap js functions that have transactions / side effects.

security concern to my specific test case [https://github.com/bfilin/urplotly_test1]:
- plotly.js is happy with a div tag and an id that was generated in urweb via fresh
- plotly then appends a new svg tag with its own id
- at this point, i believe, Ur/Web is not even aware of the new tag/id
- can things go terribly wrong with with this new svg that, any possible abuse cases?

Thank you.

**Comment by achlipala** [comment]
Well, let's see.  All of Ur/Web's IDs are decimal representations of integers.  Is it easy enough to see that the library you want to wrap never uses integers as IDs?

**Comment by bfilin** [comment]
I do not expect to see integer-only IDs from plotly; IDs that are generated by plotly.js are concatenation of ascii lowercase letters, hyphens and random hexadecimal strings ( from their custom randstr() function). 

Is this for the purposes of avoiding ID collision? Which is to say, make sure that  IDs generated by plotly library do not conflict with Ur/Web's fresh() IDs.  Or am I missing something else.

Thank you.

**Comment by achlipala** [comment]
Yes, I am "revealing" that Ur/Web IDs are all decimal representations of integers.  There will be no collisions with other systems that use disjoint ID namespaces.

**Comment by bfilin** [comment]
Thank you for your guidance. I'll aim for option 2. 
Closing.
